### PR TITLE
go: update to 1.13

### PR DESCRIPTION
**Pull request by hasheddan**
Adds support for go [1.13](https://golang.org/doc/go1.13) and updates build system to use it.

### CODE REVIEW

**Comment by negz** [comment]
@hasheddan Does Go 1.13 appear to work fine for Crossplane and friends? I've heard a few stories about it being a bit of a painful upgrade compared to previous Go versions.

**Comment by hasheddan** [comment]
@negz I don't see anything in the release notes that should cause issues, and I am using 1.13 locally, but I will make sure to test and make sure

**Comment by displague** [comment]
I had to rebase off master, because crossplane expects `build` to have `KUSTOMIZE` set.. After doing so:

```
$ make reviewable 
11:18:57 [ .. ] go generate linux_amd64
apis/storage/v1alpha1/zz_generated.claim.go
apis/stacks/v1alpha1/zz_generated.deepcopy.go
apis/workload/v1alpha1/zz_generated.deepcopy.go
apis/database/v1alpha1/zz_generated.claim.go
apis/cache/v1alpha1/zz_generated.claim.go
apis/compute/v1alpha1/zz_generated.claim.go
11:19:01 [ OK ] go generate linux_amd64
11:19:01 [ .. ] Annotating generated StackInstall CRD manifests
/home/marques/.local/share/go/src/github.com/crossplaneio/crossplane/.cache/tools/linux_amd64/kustomize-v3.3.0 build cluster/charts -o /tmp/tmp.7lBdeqGztr
mv /tmp/tmp.7lBdeqGztr/apiextensions.k8s.io_v1beta1_customresourcedefinition_clusterstackinstalls.stacks.crossplane.io.yaml cluster/charts/crossplane/templates/crds/stacks.crossplane.io_clusterstackinstalls.yaml
mv /tmp/tmp.7lBdeqGztr/apiextensions.k8s.io_v1beta1_customresourcedefinition_stackinstalls.stacks.crossplane.io.yaml cluster/charts/crossplane/templates/crds/stacks.crossplane.io_stackinstalls.yaml
11:19:01 [ OK ] Annotated generated StackInstall CRD manifests
==> Linting /home/marques/.local/share/go/src/github.com/crossplaneio/crossplane/cluster/charts/crossplane
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, no failures
11:19:01 [ .. ] verify dependencies have expected content
all modules verified
11:19:03 [ OK ] go modules dependencies verified
11:19:03 [ .. ] golangci-lint
WARN [runner/megacheck] Can't run megacheck because of compilation errors in packages [github.com/crossplaneio/crossplane/apis/cache/v1alpha1 github.com/crossplaneio/crossplane/apis/cache github.com/crossplaneio/crossplane/apis/compute/v1alpha1 github.com/crossplaneio/crossplane/apis/compute github.com/crossplaneio/crossplane/apis/database/v1alpha1 github.com/crossplaneio/crossplane/apis/database github.com/crossplaneio/crossplane/apis/kubernetes/v1alpha1 github.com/crossplaneio/crossplane/apis/kubernetes github.com/crossplaneio/crossplane/apis/stacks github.com/crossplaneio/crossplane/apis/storage/v1alpha1 github.com/crossplaneio/crossplane/apis/storage github.com/crossplaneio/crossplane/apis/workload github.com/crossplaneio/crossplane/apis github.com/crossplaneio/crossplane/pkg/controller/stacks github.com/crossplaneio/crossplane/pkg/controller/workload github.com/crossplaneio/crossplane/apis/stacks/v1alpha1 [github.com/crossplaneio/crossplane/apis/stacks/v1alpha1.test] github.com/crossplaneio/crossplane/apis/workload/v1alpha1 [github.com/crossplaneio/crossplane/apis/workload/v1alpha1.test] github.com/crossplaneio/crossplane/pkg/controller/stacks/install [github.com/crossplaneio/crossplane/pkg/controller/stacks/install.test] github.com/crossplaneio/crossplane/pkg/controller/stacks/stack [github.com/crossplaneio/crossplane/pkg/controller/stacks/stack.test] github.com/crossplaneio/crossplane/pkg/controller/workload/kubernetes/application [github.com/crossplaneio/crossplane/pkg/controller/workload/kubernetes/application.test] github.com/crossplaneio/crossplane/pkg/controller/workload/kubernetes/resource [github.com/crossplaneio/crossplane/pkg/controller/workload/kubernetes/resource.test] github.com/crossplaneio/crossplane/pkg/controller/workload/kubernetes/scheduler [github.com/crossplaneio/crossplane/pkg/controller/workload/kubernetes/scheduler.test] github.com/crossplaneio/crossplane/pkg/stacks [github.com/crossplaneio/crossplane/pkg/stacks.test] github.com/crossplaneio/crossplane/pkg/stacks/walker [github.com/crossplaneio/crossplane/pkg/stacks/walker.test]]: apis/cache/v1alpha1/doc.go:1: /snap/go/4762/src/bytes/reader.go:98:18: DecodeRune not declared by package utf8 and 2159 more errors: run `golangci-lint run --no-config --disable-all -E typecheck` to see all errors 
apis/cache/v1alpha1/doc.go:1: /snap/go/4762/src/fmt/scan.go:334:15: RuneLen not declared by package utf8 (typecheck)
/*
apis/cache/cache.go:1: /snap/go/4762/src/strings/strings.go:980:20: DecodeRuneInString not declared by package utf8 (typecheck)
/*
apis/compute/v1alpha1/doc.go:1: /snap/go/4762/src/strings/strings.go:980:20: DecodeRuneInString not declared by package utf8 (typecheck)
/*
apis/compute/compute.go:1: /snap/go/4762/src/strings/strings.go:980:20: DecodeRuneInString not declared by package utf8 (typecheck)
/*
apis/database/v1alpha1/doc.go:1: /snap/go/4762/src/strings/strings.go:980:20: DecodeRuneInString not declared by package utf8 (typecheck)
/*
apis/database/database.go:1: /snap/go/4762/src/bytes/reader.go:98:18: DecodeRune not declared by package utf8 (typecheck)
/*
apis/kubernetes/v1alpha1/doc.go:1: /snap/go/4762/src/strconv/quote.go:405:12: ValidString not declared by package utf8 (typecheck)
/*
apis/kubernetes/kubernetes.go:1: /snap/go/4762/src/strconv/quote.go:405:12: ValidString not declared by package utf8 (typecheck)
/*
apis/stacks/v1alpha1/zz_generated.deepcopy.go:443:14: undeclared name: `v1` (typecheck)
                *out = new(v1.ObjectReference)
                           ^
apis/stacks/stacks.go:1: /snap/go/4762/src/go/doc/example.go:140:18: DecodeRuneInString not declared by package utf8 (typecheck)
/*
apis/storage/v1alpha1/doc.go:1: /snap/go/4762/src/strings/strings.go:980:20: DecodeRuneInString not declared by package utf8 (typecheck)
/*
apis/storage/storage.go:1: /snap/go/4762/src/unicode/utf8/utf8.go:28:8: expected ';', found b00000000 (typecheck)
/*
apis/workload/workload.go:1: /snap/go/4762/src/strconv/quote.go:405:12: ValidString not declared by package utf8 (typecheck)
/*
apis/workload/v1alpha1/zz_generated.deepcopy.go:220:14: undeclared name: `v1` (typecheck)
                *out = new(v1.LabelSelector)
                           ^
apis/apis.go:1: /snap/go/4762/src/strings/strings.go:980:20: DecodeRuneInString not declared by package utf8 (typecheck)
/*
pkg/controller/stacks/stacks.go:1: .work/pkg/pkg/mod/github.com/gogo/protobuf@v1.2.2-0.20190723190241-65acae22fc9d/proto/text_parser.go:261:15: DecodeRuneInString not declared by package utf8 (typecheck)
/*
pkg/controller/workload/workload.go:1: /snap/go/4762/src/fmt/scan.go:334:15: RuneLen not declared by package utf8 (typecheck)
/*
cmd/crossplane/main.go:1: /snap/go/4762/src/unicode/utf8/utf8.go:28:8: expected ';', found b00000000 (typecheck)
/*
pkg/controller/stacks/install/installjob.go:1: /snap/go/4762/src/strconv/quote.go:405:12: ValidString not declared by package utf8 (typecheck)
/*
pkg/controller/stacks/stack/stack.go:1: /snap/go/4762/src/fmt/scan.go:334:15: RuneLen not declared by package utf8 (typecheck)
/*
pkg/controller/workload/kubernetes/application/application.go:1: /snap/go/4762/src/encoding/json/fold.go:83:20: DecodeRune not declared by package utf8 (typecheck)
/*
pkg/controller/workload/kubernetes/resource/resource.go:1: /snap/go/4762/src/bufio/scan.go:395:19: DecodeRune not declared by package utf8 (typecheck)
/*
pkg/controller/workload/kubernetes/scheduler/scheduler.go:1: /snap/go/4762/src/strings/strings.go:980:20: DecodeRuneInString not declared by package utf8 (typecheck)
/*
pkg/stacks/executorinfo.go:1: /snap/go/4762/src/path/filepath/match.go:215:15: DecodeRuneInString not declared by package utf8 (typecheck)
/*
pkg/stacks/walker/walker.go:1: /snap/go/4762/src/path/filepath/match.go:215:15: DecodeRuneInString not declared by package utf8 (typecheck)
/*
11:19:06 [FAIL]
make[1]: *** [build/makelib/golang.mk:201: go.lint] Error 1
make: *** [build/makelib/common.mk:332: lint] Error 2
```

**Comment by hasheddan** [comment]
Thanks @displague! Looks like we will need to [bump](https://github.com/golangci/golangci-lint/issues/658) `golangci-lint` version as well.

**Comment by hasheddan** [comment]
@lukeweber this is what I have been using, do you see any other changes that need to be made?

**Comment by hasheddan** [comment]
Closing this in favor of #84

**Pull request closed without merging**
